name: run-fusesoc-targets
on: [push]

jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    env:
      REPO : usbcorev
      VLNV : usbcorev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: usbcorev
      - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130 $VLNV

  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : usbcorev
      VLNV : usbcorev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: usbcorev
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV
